ALTER TABLE PlayerStageTimes ADD COLUMN Style INT DEFAULT 0;
ALTER TABLE PlayerStageTimes ADD COLUMN Mode VARCHAR(24) DEFAULT 'None';
ALTER TABLE PlayerStageTimes DROP PRIMARY KEY;
ALTER TABLE PlayerStageTimes ADD CONSTRAINT pk_Stage PRIMARY KEY (MapName, SteamID, Stage, Style, Mode);